Add release verification

diff --git a/.github/workflows/release_on_demand.yml b/.github/workflows/release_on_demand.yml
--- a/.github/workflows/release_on_demand.yml
+++ b/.github/workflows/release_on_demand.yml
@@ -101,6 +101,8 @@ jobs:
     runs-on: ubuntu-latest
     needs: 
       - build-from-main
+    outputs:
+      release_tag: ${{ steps.version.outputs }}
 
     steps:
       # TODO dive into the action as reference to implement custom actions
@@ -136,4 +138,28 @@ jobs:
           minor: ${{ steps.version.outputs.minor-version }}
           patch: ${{ steps.version.outputs.patch-version }}
 
-      # TODO test if new release version exists
+
+  verify-release:
+    runs-on: ubuntu-latest
+    needs: create-release
+    env:
+      version_tag: ${{ needs.create-release.outputs.release_tag }}
+
+    steps:
+      - name: Install GitHub CLI
+        run: sudo apt-get install gh
+
+      - name: Assert Release Tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          EXPECTED_TAG: ${{ env.version_tag.major }}.${{ env.version_tag.minor }}.${{ env.version_tag.patch }}
+        run: |
+          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
+          release_id=$(gh release view ${{ env.EXPECTED_TAG }} --json id --jq '.id')
+          if [ -z "$release_id" ]; then
+            echo "Release not found or the tag does not match."
+            exit 1
+          else
+            echo "Release found with ID: $release_id"
+          fi
+        
