Add release verification back in

diff --git a/.github/workflows/release_on_demand.yml b/.github/workflows/release_on_demand.yml
--- a/.github/workflows/release_on_demand.yml
+++ b/.github/workflows/release_on_demand.yml
@@ -218,46 +218,29 @@ jobs:
   verify-release:
     runs-on: ubuntu-latest
     needs: create-release
-    # TODO fix current errors end re-enable
-    if: false
     env:
       release_major: ${{ needs.create-release.outputs.release_major }}
       release_minor: ${{ needs.create-release.outputs.release_minor }}
       release_patch: ${{ needs.create-release.outputs.release_patch }}
 
     steps:
-      - name: Fetch Release Data
-        id: fetch-release-data
+      - name: Fetch Current Release Draft
+        id: fetch-current-release-draft
         run: |
-          RELEASES_URL="https://api.github.com/repos/${{ github.repository }}/releases"
-          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASES_URL)
+          current_release_name=$(gh api repos/octocat/Hello-World/releases --jq '.[] | select(.draft == true) | .name')
+          echo "current_release_name=$current_release_name" >> GITHUB_OUTPUT
 
-          release_info=$(echo $response | jq -r --arg TAG_NAME "${{ env.EXPECTED_TAG }}" '.[] | select(.tag_name == $TAG_NAME)')
-
-          if [ -z "$release_info" ]; then
-            echo "Error: Release with tag ${{ env.EXPECTED_TAG }} not found."
-            echo "Response: $response"
-            exit 1
-          else
-            echo "release_info=${release_info}" >> $GITHUB_ENV
-            echo "release_tag_found=true" >> $GITHUB_ENV
-          fi
-
-      # TODO implement this using `gh` tool instead - didn#t work at the time of writing returning error: failed to run git: fatal: not a git repository (or any of the parent directories): .git But cloning shouldn't be necessary here
-
-      - name: Check Release Tag
+      - name: 🔍 Check Release-Draft Name
         id: check-release-tag
-        if: steps.fetch-release-data.outputs.release_info
         env:
-          release_info: ${{ steps.fetch-release-data.outputs.release_info }}
-        run: |
-          release_tag=$(echo "${{ env.release_info }}" | jq -r .tag_name)
+          expected_release_draft: "${{ env.release_major }}.${{ env.release_minor}}.${{ env.release_patch}}"
+          current_release_draft: ${{ steps.fetch-current-release-draft.outputs.current_release_name }}
 
-          if [ "$release_tag" != "${{ env.release_major }}.${{ env.release_minor }}.${{ env.release_patch }}" ]; then
-            echo "Error: Expected tag ${{ env.release_major }}.${{ env.release_minor }}.${{ env.release_patch }}, but found $release_tag."
-            exit 1
-          else
+        run: |
+          if [ "${{ env.expected_release_draft }}" == "${{ env.current_release_draft }}" ]; then
             echo "Success: Release found with the expected tag $release_tag."
+            exit 0
           fi
-        
-# TODO get version bump proposal from labels (bug -> bump patch, ehancement -> bump minor, feature -> bump major)
+
+          echo "Error: Expected tag ${{ env.expected_release_draft }}, but found ${{ env.current_release_draft }}."
+          exit 1
