Update label checks

diff --git a/.github/workflows/release_on_demand.yml b/.github/workflows/release_on_demand.yml
--- a/.github/workflows/release_on_demand.yml
+++ b/.github/workflows/release_on_demand.yml
@@ -22,14 +22,12 @@ on:
 
 env:
   LABEL_DELIMITTER: ", "
-  # get token from secrets or input
   GH_TOKEN: ${{ secrets.token || secrets.YNPUT_BOT_TOKEN}}
   GH_USER: ${{ secrets.user || secrets.CI_USER }}
   GH_EMAIL: ${{ secrets.email || secrets.CI_EMAIL }}
   MAJOR: ${{ vars.MAJOR || inputs.major || 0 }}
   MINOR: ${{ vars.MINOR || inputs.minor || 1 }}
   PATCH: ${{ vars.PATCH || inputs.patch || 0 }}
-
   ARTIFACT_NAME: "addon-package"
 
 jobs:
@@ -151,8 +149,15 @@ jobs:
 
       - name: ❗ Validate labels
         if: ${{ steps.last_release_date.outputs.last_release_date }}
+        env:
+          LABEL_LIST: ${{ steps.merged_pr_labels.outputs.label_list }}
         run: |
-          if [ -z "${{ steps.valid_version_label.outputs.version_increment }}" ] && [ -n "${{ steps.last_release_date.outputs.last_release_date }}" ]; then
+          if -z "${{ env.LABEL_LIST }}"; then
+            echo "::error:: No PR labels found. Can't create a new release."
+            exit 1
+          fi
+
+          if -z "${{ steps.valid_version_label.outputs.version_increment }}"; then
             # TODO Format using line breaks - not supported by annotations
             echo "::error:: No valid versioning labels found in PRs. Only found these labels: ${{ steps.valid_version_label.outputs.pr_labels }}. Are you sure you want to create a new release?"
             exit 1
@@ -160,7 +165,7 @@ jobs:
 
 
   update-version-tag:
-    # TODO ctreamline this execution to not require empty runs
+    # TODO streamline this execution to not require empty runs
     runs-on: ubuntu-latest
     needs: get-version-increment
     env:
