Split release info fetch and assertion

diff --git a/.github/workflows/release_on_demand.yml b/.github/workflows/release_on_demand.yml
--- a/.github/workflows/release_on_demand.yml
+++ b/.github/workflows/release_on_demand.yml
@@ -150,28 +150,40 @@ jobs:
       release_patch: ${{ needs.create-release.outputs.release_patch }}
 
     steps:
-      # TODO implement this using `gh` tool instead - didn#t work at the time of writing returning error: failed to run git: fatal: not a git repository (or any of the parent directories): .git But cloning shouldn't be necessary here
-      - name: Assert Release Tag from Draft
+      - name: Fetch Release Data
+        id: fetch-release-data
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          EXPECTED_TAG: ${{ env.release_major }}.${{ env.release_minor }}.${{ env.release_patch }}
+          EXPECTED_TAG: "${{ env.release_major }}.${{ env.release_minor }}.${{ env.release_patch }}"
         run: |
           RELEASES_URL="https://api.github.com/repos/${{ github.repository }}/releases"
           response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASES_URL)
 
           release_info=$(echo $response | jq -r --arg TAG_NAME "${{ env.EXPECTED_TAG }}" '.[] | select(.tag_name == $TAG_NAME)')
-          
+
           if [ -z "$release_info" ]; then
             echo "Error: Release with tag ${{ env.EXPECTED_TAG }} not found."
             echo "Response: $response"
             exit 1
           else
-            release_tag=$(echo $release_info | jq -r .tag_name)
-            if [ "$release_tag" != "${{ env.EXPECTED_TAG }}" ]; then
-              echo "Error: Expected tag ${{ env.EXPECTED_TAG }}, but found $release_tag."
-              exit 1
-            else
-              echo "Success: Release found with the expected tag $release_tag."
-            fi
+            echo "release_info=${release_info}" >> $GITHUB_ENV
+            echo "release_tag_found=true" >> $GITHUB_ENV
+          fi
+          
+      # TODO implement this using `gh` tool instead - didn#t work at the time of writing returning error: failed to run git: fatal: not a git repository (or any of the parent directories): .git But cloning shouldn't be necessary here
+
+      - name: Check Release Tag
+        id: check-release-tag
+        if: steps.fetch-release-data.outputs.release_info
+        env:
+          release_info: ${{ steps.fetch-release-data.outputs.release_info }}
+        run: |
+          release_tag=$(echo "${{ env.release_info }}" | jq -r .tag_name)
+
+          if [ "$release_tag" != "${{ env.release_major }}.${{ env.release_minor }}.${{ env.release_patch }}" ]; then
+            echo "Error: Expected tag ${{ env.release_major }}.${{ env.release_minor }}.${{ env.release_patch }}, but found $release_tag."
+            exit 1
+          else
+            echo "Success: Release found with the expected tag $release_tag."
           fi
         
